### ISSUE TITLE
Unable to use with module lazy loading

### ISSUE THREAD

**Issue by pierpa68** [annapogorelova/ng2-go-top-button#1]
Hi,

first of all thanks for your great work.

I think you should include the "CommonModule" instead of the "BrowserModule", otherwise it is impossible to use your component in a lazy loaded module, as stated in the official documentation: [https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-browser-vs-common-module](url)

Anyway, great component!

**Comment by annapogorelova** [comment]
@pierpa68 , thanks for spotting this!
