### ISSUE TITLE
'SafeHtml' is declared but never used.

### ISSUE THREAD

**Issue by Walteroos2** [annapogorelova/ng2-go-top-button#12]
ERROR in node_modules/ng2-go-top-button/src/safe-html.pipe.ts(1,23): error TS6133: 'SafeHtml' is declared but never used.

Anyone encounter this issue?

**Comment by annapogorelova** [comment]
@Walteroos2  which version of the module are you using?

**Comment by annapogorelova** [comment]
#15 should fix it because I have removed the SafeHtml at all.
