### ISSUE TITLE
Default attribute styles

### ISSUE THREAD

**Issue by riwos** [annapogorelova/ng2-go-top-button#18]
Hi,

I think you can extend your awesome directive regard styles. You've defined default styles like this:

> this.defaultStyles = {
>             'position': 'fixed',
>             'top': '50%',
>             'bottom': '50%',
>             'right': '0',
>             'width': '35px',
>             'height': '35px',
>             'line-height': '35px',
>             'text-decoration': 'none',
>             'color': 'white',
>             'background': 'rgba(0, 0, 0, 0.3)',
>             'border': 'none',
>             'border-radius': '3px 0 0 3px'
>         };

In my case I do not need your default styles. I think that should be optional. 
That would be great if you can implement the following three cases

1. If you do not define any styles the attribute style should not be rendered on html tag.
2. That option will be the best for me. If I can put names of classes from css in current button attribute i.e:` [styles]={ 'classA classB classC' }`
3. The style configuration that works as standard functionality now.

What do you think ?? This is only my proposal ;)

**Comment by annapogorelova** [comment]
@riwos Thank you for your feedback. You are right about the default styles being a bit redundant. I will think about making the syntax a bit more flexible and maybe release the new functionality in the next major version of the directive (v5.0.0).

**Comment by annapogorelova** [comment]
Hi @riwos . I'm sorry for being so late with this feature, but it is available now in [v4.2.1](https://github.com/annapogorelova/ng2-go-top-button/releases/tag/v4.2.1).

**Comment by riwos** [comment]
Thanks a lot ;)
