### ISSUE TITLE
AOT Build

### ISSUE THREAD

**Issue by riwos** [annapogorelova/ng2-go-top-button#20]
**After when I invoked this call from CLI:**

"ng build -prod -aot -vc -cc -dop --buildOptimizer"

**after I've got:**

"ERROR in : Can't bind to 'classNames' since it isn't a known property of 'go-top-button'.
1. If 'go-top-button' is an Angular component and it has 'classNames' input, then verify that it is part of this module.
2. If 'go-top-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" </div>
    <go-top-button [animate]="true" [speed]="20" [acceleration]="5" [scrollDistance]="300" [ERROR ->][classNames]="'arrow-go-to-top active'">
        <i class="fa fa-angle-up"></i>
    </go-top-button")"

**My component.ts has:**

@Component({
'other things'
  encapsulation: ViewEncapsulation.None
})

In development mode everything works right. Any suggestions ??

**Comment by annapogorelova** [comment]
@riwos thanks for letting me know, I'll check this issue.

**Comment by p4pupro** [comment]
Hi,

I am getting same error, just on prod, in dev mode work fine!!

**Comment by annapogorelova** [comment]
Hey, guys, I have just released [v6.0.0](https://github.com/annapogorelova/ng2-go-top-button/releases/tag/v6.0.0), this one should be fixed there, check it out.

**Comment by annapogorelova** [comment]
@p4pupro I was making some intermediate prerelease changes today. The property is still called `classNames`. Please, take the latest 6.0.0 version. Thanks.

**Comment by p4pupro** [comment]
@annapogorelova yes!!, it fixed. Thanks you! ;)
