### ISSUE TITLE
Cannot update to Angular 7.x

### ISSUE THREAD

**Issue by davidremus** [annapogorelova/ng2-go-top-button#24]
Hello,
I have a problem when i try to upgrade project to Angular 7.x, because it's not compatible with typescript 3.1.6..
"Package "ng2-go-top-button" has an incompatible peer dependency to "typescript" (requires "^2.x", would install "3.1.6")."
"Incompatible peer dependencies found. See above."

It works only if i use '--force'

Any suggestions, please?
 Thank you advice!

**Comment by annapogorelova** [comment]
@davidremus Thank you for reporting the issue. I didn't make any Angular 7.x updates yet, will have a look into this a bit later. Meanwhile, you are welcome to do the pull request if it's urgent for you.

**Comment by tsetiz** [comment]
Please upgrade to angular 7

**Comment by annapogorelova** [comment]
Fixed in **v7.0.1**
