### ISSUE TITLE
Upgrade to Angular 8.x

### ISSUE THREAD

**Issue by khobar** [annapogorelova/ng2-go-top-button#27]
Could you please upgrade to Angular 8.x ?

Component itself works fine after upgrading whole app 
But there are some warnings

    npm WARN ng2-go-top-button@7.1.0 requires a peer of @angular/animations@^7.x but none is installed. You must install peer dependencies yourself.
    npm WARN ng2-go-top-button@7.1.0 requires a peer of @angular/common@^7.x but none is installed. You must install peer dependencies yourself.
    npm WARN ng2-go-top-button@7.1.0 requires a peer of @angular/core@^7.x but none is installed. You must install peer dependencies yourself.
    npm WARN ng2-go-top-button@7.1.0 requires a peer of @angular/platform-browser@^7.x but none is installed. You must install peer dependencies yourself.
    npm WARN ng2-go-top-button@7.1.0 requires a peer of typescript@>=3.1.1 <3.3.0 but none is installed. You must install peer dependencies yourself.
    npm WARN ng2-go-top-button@7.1.0 requires a peer of zone.js@^0.8.x but none is installed. You must install peer dependencies yourself.

Best Regards

**Comment by annapogorelova** [comment]
Ok, thanks, I will take a look.

**Comment by annapogorelova** [comment]
@khobar I have updated dependencies, let me know if v8.0.0 works fine for you.

**Comment by khobar** [comment]
> @khobar I have updated dependencies, let me know if v8.0.0 works fine for you.

Almost there :)

    npm WARN ng2-go-top-button@8.0.0 requires a peer of typescript@~3.3.0 but none is installed. You must install peer dependencies yourself.
According to https://update.angular.io/#7.2:8.0 

> Angular 8 now uses TypeScript 3.4, read more about errors that might arise from improved type checking.

In my case I already have : 

    "devDependencies": {
    ...
    "typescript": "~3.4.5"}

Best Regards

**Comment by annapogorelova** [comment]
Done.

**Comment by khobar** [comment]
Now flawless :)

Thanks for upgrade
