### ISSUE TITLE
Remove Typescript peer dependency

### ISSUE THREAD

**Issue by DavidGangel** [annapogorelova/ng2-go-top-button#28]
Hi,

would it be possible to remove the typescript peer dependency from the package.json?

"peerDependencies": {
    "@angular/animations": "^8.0",
    "@angular/common": "^8.0",
    "@angular/core": "^8.0",
    "@angular/platform-browser": "^8.0",
    "rxjs": "^6.0",
    "typescript": "~3.4.0",
    "zone.js": "^0.9.0"
  },

you already have a dev dependency over typescript:
"devDependencies": {
    "@angular/animations": "^8.0.3",
    "@angular/common": "^8.0.3",
    "@angular/compiler": "^8.0.3",
    "@angular/compiler-cli": "^8.0.3",
    "@angular/core": "^8.0.3",
    "@angular/platform-browser": "^8.0.3",
    "@types/core-js": "^2.5.0",
    "rxjs": "^6.5.2",
    "tsickle": "^0.34.3",
    "typescript": "^3.4.5",
    "zone.js": "^0.9.1"
  }

This blocks me to upgrade ng-bootstrap.

**Comment by annapogorelova** [comment]
Fixed in v8.0.5 https://github.com/annapogorelova/ng2-go-top-button/releases/tag/v8.0.5
