### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by mriel** [annapogorelova/ng2-go-top-button#3]
There seems to be an issue when trying to add accessibility aria attributes to the HTML. I am currently trying to do this:

`[html]="'<i class=\'fa fa-arrow-up\' aria-hidden=\'true\' aria-label=\'go to top of the page\'></i>'"`

but the attributes are not showing up in the output HTML.

**Comment by annapogorelova** [comment]
@mriel thanks for noticing it! Fixed.
