### ISSUE TITLE
Add Angular 9 support

### ISSUE THREAD

**Issue by bsautel** [annapogorelova/ng2-go-top-button#32]
Does not work with Angular 9:
> Compiling ng2-go-top-button : main as commonjs
> ERROR in getInternalNameOfClass() called on a non-ES5 class: expected GoTopButton to have an inner class declaration

Would it be compatible to make a new version compatible with Angular 9?

Thanks a lot!

**Comment by bsautel** [comment]
I created pull request #33 that adds Angular 9 support.

@annapogorelova could you have a look at it please?

**Comment by annapogorelova** [comment]
Hi, @bsautel, sorry for the late reply and thank you for your work. I have created a new NPM package [ng-go-top-button](https://www.npmjs.com/package/ng-go-top-button) which corresponds to the new Angular library format and supports Angular 9.
