### ISSUE TITLE
Error in Angular 5.0.1/CLI 1.5

### ISSUE THREAD

**Issue by jackjamieson** [annapogorelova/ng2-go-top-button#6]
> ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in C:/Users/jjamieson/Desktop/Shared/VSIP-birth-angular/BirthRegistryUI/node_modules/ng2-go-top-button/node_modules/@angular/core/core.d.ts, resolving symbol GoTopButtonModule in C:/Users/jjamieson/Desktop/Shared/VSIP-birth-angular/BirthRegistryUI/node_modules/ng2-go-top-button/src/go-top-button.module.ts, resolving symbol GoTopButtonModule in C:/Users/jjamieson/Desktop/Shared/VSIP-birth-angular/BirthRegistryUI/node_modules/ng2-go-top-button/src/go-top-button.module.ts

Getting this error now with the latest version of Angular.  You may want to consider updating the package's local Angular version as well.

**Comment by annapogorelova** [comment]
@jackjamieson thanks for the report, I'll check.

**Comment by jackjamieson** [comment]
Thanks @annapogorelova it also may not be Angular 5 itself but Angular CLI which I'm also using the newest 1.5 release.

**Comment by annapogorelova** [comment]
@jackjamieson I have recently published a new version **3.0.0**. Please, try it and see if the issue still exists. Thank you.

**Comment by jackjamieson** [comment]
I am seeing this now 

```
ERROR in ./node_modules/ng2-go-top-button/src/go-top-button.component.ts
Module build failed: Error: C:\Users\jjamieson\Desktop\Shared\BIRTH-NG5\OVSR-UI-Birth\node_modules\ng2-go-top-button\src\go-top-button.component.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\jjamieson\Desktop\Shared\BIRTH-NG5\OVSR-UI-Birth\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (C:\Users\jjamieson\Desktop\Shared\BIRTH-NG5\OVSR-UI-Birth\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/ng2-go-top-button/index.js 3:32-72
 @ ./src/app/modules/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./node_modules/ng2-go-top-button/src/go-top-button.module.ts
Module build failed: Error: C:\Users\jjamieson\Desktop\Shared\BIRTH-NG5\OVSR-UI-Birth\node_modules\ng2-go-top-button\src\go-top-button.module.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\jjamieson\Desktop\Shared\BIRTH-NG5\OVSR-UI-Birth\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (C:\Users\jjamieson\Desktop\Shared\BIRTH-NG5\OVSR-UI-Birth\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/ng2-go-top-button/index.js 5:29-66
 @ ./src/app/modules/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.
```

**Comment by annapogorelova** [comment]
@jackjamieson it's a temporary issue with angular cli. Add this to your tsconfig.json^

**Comment by annapogorelova** [comment]
@jackjamieson It's a temporary issue with the new version of angular cli. Please add this to your tsconfig.json

```
"include": [
    ...,
    "node_modules/ng2-go-top-button/src/**/*"
]
```
(it's described in the updated README of ng2-go-top-button)

**Comment by jackjamieson** [comment]
Thanks @annapogorelova that works.  That solution is listed as the workaround in the comment that I linked 

> That being said, maybe you can try adding it to the include array. But I can't guarantee that will work in the future because it's still an incorrectly packaged library.

For now just happy I can move on, thanks!

**Comment by annapogorelova** [comment]
@jackjamieson Thanks for providing that information, I'll change the directory structure of the library to prevent any further issues with that.
