### ISSUE TITLE
No provider for DomSanitizer

### ISSUE THREAD

**Issue by jackjamieson** [annapogorelova/ng2-go-top-button#8]
`ERROR Error: StaticInjectorError[DomSanitizer]: 
  StaticInjectorError[DomSanitizer]: 
    NullInjectorError: No provider for DomSanitizer!`

Getting this error now with 5.0.0-beta.2 and CLI 1.5.0

`
@NgModule({
    imports: [CommonModule],
    declarations: [GoTopButton, Safe],
    exports: [GoTopButton]
})`

**Comment by annapogorelova** [comment]
I have removed `DomSanitizer` and `SafeHtml` in **v4.0.0** so this issue should hopefully be gone. And I'm sorry for the late reply, I couldn't reproduce it on my side.
